version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_inventory_app
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    container_name: product_inventory_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: product_inventory_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: product_inventory
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: product_inventory_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: